
// このファイルは自動生成されています
const projects = [
  {
    id: "1",
    name: "Eコマースサイト",
    description: "Next.jsとSupabaseを使用した完全なEコマースプラットフォーム",
    longDescription:
      "このプロジェクトでは、Next.jsとSupabaseを使用して完全なEコマースプラットフォームを構築しました。ユーザー認証、商品の閲覧、カート機能、注文処理など、Eコマースサイトの主要機能をすべて実装しています。また、管理者ダッシュボードでは商品の追加、在庫管理、注文状況の確認が可能です。",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Supabase",
      "Material-UI",
      "Stripe",
    ],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/ecommerce-demo",
    githubLink: "https://github.com/yourusername/ecommerce-project",
    featured: true,
    createdAt: "2023-08-15",
  },
  {
    id: "2",
    name: "タスク管理アプリ",
    description:
      "Reactとローカルストレージを使用したシンプルなタスク管理アプリ",
    longDescription:
      "このタスク管理アプリは、Reactを使用して構築されています。ユーザーはタスクの追加、編集、削除、完了のマークができます。また、タスクをカテゴリー別に分類したり、期限でソートしたりすることも可能です。データはローカルストレージに保存されるため、ページを更新してもタスクは保持されます。",
    technologies: ["React", "JavaScript", "CSS", "LocalStorage"],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/task-app-demo",
    githubLink: "https://github.com/yourusername/task-manager",
    createdAt: "2023-05-20",
  },
  {
    id: "3",
    name: "ブログサイト",
    description: "Next.jsとPrismaを使用した個人ブログサイト",
    longDescription:
      "このブログサイトは、Next.jsとPrismaを使用して構築されています。記事の投稿、編集、削除機能があり、マークダウン形式での記事作成をサポートしています。また、カテゴリーやタグでの記事の分類、検索機能も実装しています。コメント機能も備えており、読者とのインタラクションが可能です。",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Tailwind CSS",
    ],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/blog-demo",
    githubLink: "https://github.com/yourusername/blog-site",
    featured: true,
    createdAt: "2023-11-10",
  },
  {
    id: "4",
    name: "天気予報アプリ",
    description: "React NativeとWeather APIを使用したモバイル天気予報アプリ",
    longDescription:
      "このモバイルアプリは、React Nativeを使用して構築され、Weather APIと連携して現在の天気と5日間の予報を表示します。ユーザーは位置情報を共有するか、手動で都市を検索して天気を確認できます。また、お気に入りの都市を保存して素早くアクセスすることも可能です。",
    technologies: ["React Native", "JavaScript", "API Integration", "Expo"],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/weather-app-demo",
    githubLink: "https://github.com/yourusername/weather-app",
    createdAt: "2023-03-05",
  },
  {
    id: "5",
    name: "チャットアプリ",
    description: "Node.jsとSocket.IOを使用したリアルタイムチャットアプリ",
    longDescription:
      "このチャットアプリは、Node.jsとSocket.IOを使用して構築されたリアルタイム通信が可能なウェブアプリケーションです。ユーザーは登録してログインした後、異なるチャットルームに参加して他のユーザーとメッセージをやり取りできます。また、プライベートメッセージやファイル共有機能も実装しています。",
    technologies: ["Node.js", "Express", "Socket.IO", "MongoDB", "React"],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/chat-app-demo",
    githubLink: "https://github.com/yourusername/chat-application",
    createdAt: "2023-09-30",
  },
  {
    id: "6",
    name: "SNSアプリケーション",
    description: "Vue.jsとFirebaseを使用したソーシャルネットワーキングアプリ",
    longDescription:
      "このSNSアプリケーションはVue.jsとFirebaseを使用して構築されています。ユーザーは投稿の作成、他のユーザーのフォロー、メッセージの送信などができます。リアルタイムデータベースを活用してリアルタイム更新を実現しています。",
    technologies: ["Vue.js", "Firebase", "Vuex", "JavaScript", "CSS"],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/sns-app-demo",
    githubLink: "https://github.com/yourusername/sns-application",
    createdAt: "2023-12-15",
  },
  {
    id: "7",
    name: "GraphQLベースのAPI",
    description: "Node.jsとGraphQLを使用したスケーラブルなAPI",
    longDescription:
      "このプロジェクトでは、Node.jsとGraphQLを使用してスケーラブルなAPIを設計・実装しました。REST APIと比較して、必要なデータのみを取得できる効率的な設計になっています。MongoDB Atlas上に構築され、AWS Lambdaでサーバーレスデプロイを実現しています。",
    technologies: [
      "Node.js",
      "GraphQL",
      "Apollo Server",
      "MongoDB",
      "AWS Lambda",
    ],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/graphql-api-demo",
    githubLink: "https://github.com/yourusername/graphql-api",
    featured: true,
    createdAt: "2024-01-20",
  },
  {
    id: "8",
    name: "クロスプラットフォームモバイルアプリ",
    description: "Flutterを使用して構築したモバイルアプリ",
    longDescription:
      "このクロスプラットフォームモバイルアプリはFlutterを使用して開発されました。iOSとAndroid両方のプラットフォームで一貫したユーザー体験を提供します。Firebase Authenticationで認証を実装し、Cloud Firestoreでリアルタイムデータ同期を実現しています。",
    technologies: [
      "Flutter",
      "Dart",
      "Firebase",
      "Firebase Auth",
      "Cloud Firestore",
    ],
    screenshots: ["/images/dummy/icon.png", "/images/dummy/icon.png"],
    demoLink: "https://example.com/flutter-app-demo",
    githubLink: "https://github.com/yourusername/flutter-app",
    createdAt: "2023-10-05",
  },
];

const skills = [
  {
    name: "React",
    level: 85,
    icon: "react",
    category: "frontend",
  },
  {
    name: "Next.js",
    level: 80,
    icon: "nextjs",
    category: "frontend",
  },
  {
    name: "TypeScript",
    level: 75,
    icon: "typescript",
    category: "frontend",
  },
  {
    name: "JavaScript",
    level: 90,
    icon: "javascript",
    category: "frontend",
  },
  {
    name: "HTML5",
    level: 95,
    icon: "html5",
    category: "frontend",
  },
  {
    name: "CSS3",
    level: 90,
    icon: "css3",
    category: "frontend",
  },
  {
    name: "Node.js",
    level: 70,
    icon: "nodejs",
    category: "backend",
  },
  {
    name: "Express",
    level: 65,
    icon: "express",
    category: "backend",
  },
  {
    name: "PostgreSQL",
    level: 60,
    icon: "postgresql",
    category: "database",
  },
  {
    name: "MongoDB",
    level: 55,
    icon: "mongodb",
    category: "database",
  },
  {
    name: "Supabase",
    level: 75,
    icon: "supabase",
    category: "database",
  },
  {
    name: "Git",
    level: 85,
    icon: "git",
    category: "devops",
  },
  {
    name: "Docker",
    level: 50,
    icon: "docker",
    category: "devops",
  },
  {
    name: "Material-UI",
    level: 80,
    icon: "materialui",
    category: "frontend",
  },
  {
    name: "Tailwind CSS",
    level: 70,
    icon: "tailwindcss",
    category: "frontend",
  },
  {
    name: "Vue.js",
    level: 65,
    icon: "vuejs",
    category: "frontend",
  },
  {
    name: "Angular",
    level: 60,
    icon: "angular",
    category: "frontend",
  },
  {
    name: "Redux",
    level: 75,
    icon: "redux",
    category: "frontend",
  },
  {
    name: "Django",
    level: 55,
    icon: "django",
    category: "backend",
  },
  {
    name: "GraphQL",
    level: 70,
    icon: "graphql",
    category: "backend",
  },
  {
    name: "Firebase",
    level: 80,
    icon: "firebase",
    category: "database",
  },
  {
    name: "AWS",
    level: 65,
    icon: "aws",
    category: "devops",
  },
  {
    name: "GitHub Actions",
    level: 70,
    icon: "github",
    category: "devops",
  },
  {
    name: "Jest",
    level: 75,
    icon: "jest",
    category: "other",
  },
  {
    name: "Flutter",
    level: 50,
    icon: "flutter",
    category: "other",
  },
];

const profile = {
  name: "山田 太郎",
  title: "フロントエンドデベロッパー",
  bio: "フロントエンド開発に情熱を持つ開発者です。ユーザー体験を重視したWebアプリケーションの構築を得意としています。新しい技術を学ぶことが好きで、常に最新のトレンドをキャッチアップしています。以前はIT企業でフルスタック開発者として3年間勤務した経験があり、現在はフリーランスとして様々なプロジェクトに携わっています。",
  email: "example@example.com",
  github: "https://github.com/yourusername",
  linkedin: "https://linkedin.com/in/yourusername",
  twitter: "https://twitter.com/yourusername",
  avatar: "/images/icon.png",
};

module.exports = { projects, skills, profile };
